CREATE DATABASE IF NOT EXISTS sis_acad;

CREATE TABLE IF NOT EXISTS sis_acad.tb_usuario(
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(35) NOT NULL,
  email VARCHAR(60) NOT NULL,
  telefone INT(30) NOT NULL,
  cpf INT(30) NOT NULL,
  senha VARCHAR(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;